### ISSUE TITLE
amqp: vhost in channel binding

### ISSUE THREAD

**Issue by mr-nuno** [asyncapi/bindings#116]
#### Describe the bug
When looking at the `channelBindings` for a `amqp` the `vhost` is on the channel level. But the `vhost` is really part of the `amqp`  connection i.e. part of the authentication. 

```
channels:
  user/signedup:
    bindings:
      amqp:
        is: routingKey
        queue:
          name: my-queue-name
          durable: true
          exclusive: true
          autoDelete: false
          vhost: /
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
        bindingVersion: 0.2.0
```

For example,  `user` and `password` and `vhost` is used when authenticating against a amqp RabbitMQ broker. I don´t think the `vhost` is a part of the channel? When you look at the `server` part for a `amqp` broker. The `vhost` is already part of the `url`

```
servers:
  production:
    url: goose.rmq2.cloudamqp.com/hohmawct
    protocol: amqps
```

#### Expected behavior
Remove `vhost` from the `channelBindings`
```
channels:
  user/signedup:
    bindings:
      amqp:
        is: routingKey
        queue:
          name: my-queue-name
          durable: true
          exclusive: true
          autoDelete: false
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
        bindingVersion: 0.2.0
```

**Comment by smoya** [comment]
@mr-nuno thanks for submitting this issue. I took a quick look into it and indeed it makes sense to me that the virtual host shouldn't be in channel binding but instead, be grabbed from the server URL whenever is needed.
Starting from AsyncAPI spec `v2.1.0`, channels can be assigned to servers (see https://github.com/asyncapi/spec/pull/531), so in case any tool needs to know about the virtual host from a channel point of view, that could be definitely done thanks to it.

I think I'm ok with this suggestion, however, I'm not an expert on AMQP. Let's see what others say so I'm pinging some people that at some point have been involved with this particular binding: @iancooper @olvlvl @ericsampson

**Comment by smoya** [comment]
> Would you never want to have two channels use different vhost properties to the same server?
> 
> I.e. is this never a use-case 🤔?
> 
> ```yaml
> servers:
>   production:
>     url: goose.rmq2.cloudamqp.com
>     protocol: amqps
> channels:
>   user/signedup:
>     bindings:
>       amqp:
>         is: routingKey
>         queue:
>           name: my-queue-name
>           durable: true
>           exclusive: true
>           autoDelete: false
>           vhost: /hohmawct
>         bindingVersion: 0.2.0
>   user/signedup2:
>     bindings:
>       amqp:
>         is: routingKey
>         exchange:
>           name: myExchange
>           type: topic
>           durable: true
>           autoDelete: false
>           vhost: /hohmawct2
>         bindingVersion: 0.2.0
> ```

The use case on having different vhost is valid. However, you could have one server per vhost if needed.

**Comment by mr-nuno** [comment]
Good question :smiley:
What I'm probably getting at is that the `vhost` is already part of `servers`
```
servers:
  hohmawct:
    url: goose.rmq2.cloudamqp.com/hohmawct
    protocol: amqps
  hohmawct2:
    url: goose.rmq2.cloudamqp.com/hohmawct2
    protocol: amqps

```
It's not really part of the `channelsBindings`
