### ISSUE TITLE
[FEATURE REQUEST] Documentation for more than one routingKey

### ISSUE THREAD

**Issue by gustajz** [asyncapi/bindings#12]
Hi everyone

It's possible add support to documenting an exchange that contains more than one routingKey for different queues?

Proposal Example:
```
channels:
  user/signedup:
    bindings:
      amqp:
        is: routingKey
        key:
        - name: key1
          queue:
            name: my-queue-name
            durable: true
            exclusive: true
            autoDelete: false
            vhost: /
        - name: key1
          queue:
            name: my-queue-name
            durable: true
            exclusive: true
            autoDelete: false
            vhost: /
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
```

Below is a real world example:

![rabbitmq](https://user-images.githubusercontent.com/1320225/71264192-49120780-2322-11ea-9b29-5e743f7f798e.png)

Thanks!

**Comment by fmvilas** [comment]
If I understood correctly, you can already do this:

```yaml
channels:
  push/enviar-push-polling/message: # Note that slashes are converted to dots when using AMQP.
    bindings:
      amqp:
        is: routingKey
        queue:
            name: push.enviar-push-polling.queue
            durable: true
            exclusive: true
            autoDelete: false
            vhost: /
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
  push/enviar-push/message: # Note that slashes are converted to dots when using AMQP.
    bindings:
      amqp:
        is: routingKey
        queue:
            name: push.enviar-push.queue
            durable: true
            exclusive: true
            autoDelete: false
            vhost: /
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
```

Let me know if this makes sense to you.
