### ISSUE TITLE
HTTP channel binding should include a path parameter

### ISSUE THREAD

**Issue by jmcx** [asyncapi/bindings#180]
#### Reason/Context
The Kafka and googlepubsub bindings let you specify the `topic` as a separate attribute, e.g. for Kafka:

```yaml
channels:
  orders:
    bindings:
      kafka:
        topic: 'kafka-orders-topic'
```

For the HTTP binding, you must rely on the channel name to define the HTTP path. But the HTTP path can be long and technical and contain lots of slashes, meaning it isn't always very human readable, e.g.:

```yaml
channels:
  /path/path/something_here/somethingelse/orders:
```

This also makes it impossible to define a channel once but bind it to different servers with different protocols, if HTTP is one of those. 

#### Description

Would be great to have a path attribute for the HTTP binding so I can have a nice name for the channel and different value for the path, e.g.: 

```yaml
channels:
  orders:
    bindings:
      http:
        path: '/path/path/something_here/somethingelse/orders'
```
