### ISSUE TITLE
HTTP Bindings: message binding parameters mismatch

### ISSUE THREAD

**Issue by Pakisan** [asyncapi/bindings#19]
Good morning. Here is parameters mismatch in message binding section in HTTP Bindings

#### How to Reproduce
You defined next properties in [this schema](https://github.com/asyncapi/bindings/tree/master/http#message-binding-object) as allowed:
* headers
* bindingVersion

But in example you provided `meta` instead of `bindingVersion `
```yaml
channels:
  test:
    publish:
      message:
        bindings:
          http:
            headers:
              type: object
              properties:
                Content-Type:
                  type: string
                  enum: ['application/json']
            meta:
              version: '0.1.0'
```

#### Expected behavior
I think that correct example is it:
```yaml
channels:
  test:
    publish:
      message:
        bindings:
          http:
            headers:
              type: object
              properties:
                Content-Type:
                  type: string
                  enum: ['application/json']
            bindingVersion: '0.1.0'
```
