### ISSUE TITLE
Specifying payload removes `Allowed values` of  Kafka binding `key`

### ISSUE THREAD

**Issue by LittleWat** [asyncapi/bindings#197]
Hello! I am new to AsyncAPI so my usage might be wrong but let me ask a question.

#### Describe the bug
Specifying payload removes `Allowed values` of  Kafka binding `key`

<img width="725" alt="スクリーンショット 2023-04-17 17 10 41" src="https://user-images.githubusercontent.com/8979377/232428263-ec5fa230-622a-4080-a320-42ab7dc33b4d.png">

#### How to Reproduce

Using this yaml

```yaml
asyncapi: 2.6.0
info:
  title: Kafka Topics
  version: 1.0.0
  description: Kafka Topics
channels:
  sample:
    publish:
      summary: a

components:
  messages:
    sample-with-payload:
      name: sample-with-payload
      title: sample-with-payload
      summary: sample-with-payload
      contentType: avro/binary
      schemaFormat: application/vnd.apache.avro+json;version=1.9.0
      bindings:
        kafka:
          key:
            type: string
            enum: [ 'Germany', 'Austria', 'Switzerland' ]
            schemaIdLocation: 'payload'
            schemaIdPayloadEncoding: 'apicurio-new'
            schemaLookupStrategy: 'TopicIdStrategy'
      payload:
        $ref: "https://raw.githubusercontent.com/ueisele/showcase-asyncapi-api/main/schema/de/novatec/streetlight/measured/v2/LightMeasuredEvent.g1.avsc"
    sample-without-payload:
      name: sample-without-payload
      title: sample-without-payload
      summary: sample-without-payload
      contentType: avro/binary
      schemaFormat: application/vnd.apache.avro+json;version=1.9.0
      bindings:
        kafka:
          key:
            type: string
            enum: [ 'Germany', 'Austria', 'Switzerland' ]
            schemaIdLocation: 'payload'
            schemaIdPayloadEncoding: 'apicurio-new'
            schemaLookupStrategy: 'TopicIdStrategy'

```

#### Expected behavior
Allowed values should be seen even when the payload is specified.

Thank you!
