### ISSUE TITLE
add message size/length to mqtt and mqtt5

### ISSUE THREAD

**Issue by tomkralidis** [asyncapi/bindings#198]
#### Reason/Context
It would be valuable to add message size/length (in bytes) to the MQTT bindings to advertise the maximum message size a given MQTT binding accepts/emits.

#### Description
Given this is a feature/enhancement, it is not a breaking change.  Example definition:

MQTT5:
```yaml
    bindings:
      mqtt5:
        messageMaxSize: 4096
```

MQTT:
```yaml
    bindings:
      mqtt:
        messageMaxSize: 4096
```

Happy to put forth a PR if the above seems reasonable.

**Comment by pearmaster** [comment]
In MQTTv5, there is the "Maximum Packet Size" property on the CONNECT message. See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901050

So I would propose the MQTTv5 bindings follow the same terminology:
```yaml
bindings:
  mqtt5:
    maximumPacketSize: 4096
```

I'm hoping to put together a PR for MQTTv5 bindings that includes this and several other MQTTv5 properties (including user properties).  I probably will not touch the `mqtt` (v3) bindings.
