### ISSUE TITLE
Kafka Bindings: operation binding parameters mismatch

### ISSUE THREAD

**Issue by Pakisan** [asyncapi/bindings#21]
#### Describe the bug
Good morning. Here is parameters mismatch in operation binding section in HTTP Bindings

#### How to Reproduce
You defined next properties in this schema as:
* `groupId` as `String`
* `clientId` as `String`

but provides example where they are objects

```yaml
channels:
  user-signedup:
    publish:
      bindings:
        kafka:
          groupId:
            type: string
            enum: ['myGroupId']
          clientId:
            type: string
            enum: ['myClientId']
          bindingVersion: '0.1.0'
```

#### Expected behavior
but looks like they should be [Schema Object](https://www.asyncapi.com/docs/specifications/2.0.0/#schemaObject)

Am I right? If it so I will create PR with fix.

https://github.com/asyncapi/bindings/pull/25
