### ISSUE TITLE
Kafka Bindings: message binding parameters mismatch

### ISSUE THREAD

**Issue by Pakisan** [asyncapi/bindings#22]
#### Describe the bug
Good morning. Here is parameters mismatch in operation binding section in HTTP Bindings

#### How to Reproduce
You defined next property in this schema as:
* `key ` as `String`
but provides example where it is objects

```yaml
channels:
  test:
    publish:
      message:
        bindings:
          kafka:
            key:
              type: string
              enum: ['myKey']
            bindingVersion: '0.1.0'
```

#### Expected behavior
but looks like it should be [Schema Object](https://www.asyncapi.com/docs/specifications/2.0.0/#schemaObject)

Am I right? If it so I will create PR with fix.
