### ISSUE TITLE
[Docs Bug 🐞 report]: JMS Server Binding Example doesn't match AsyncAPI v3 specification

### ISSUE THREAD

**Issue by ctasada** [asyncapi/bindings#232]
### Describe the bug you found in AsyncAPI Docs.

The https://github.com/asyncapi/bindings/blob/master/jms/README.md#examples shows
```yaml
servers:
  production:
    url: jms://my-activemq-broker:61616
    protocol: jms
    protocolVersion: '1.1'
    description: The production ActiveMQ broker accessed via JMS.
```
If this object is related with https://github.com/asyncapi/bindings/blob/master/jms/README.md#server-object then the `description` field shouldn't be included (or it's missing from the Server Object definition) Also, the `url` field doesn't exist anymore in https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject being replaced by the `hosts` field.

Also, the https://github.com/asyncapi/bindings/blob/master/jms/README.md#server-binding-object points to a [Schema Array](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#schemaArray) which doesn't exist anymore. Based in the example it probably should refer to a generic `Map[string, string]` but I may be wrong there.

### Attach any resources that can help us understand the issue.

See https://github.com/asyncapi/bindings/blob/master/jms/README.md#examples

The format of https://github.com/asyncapi/bindings/blob/master/jms/README.md#examples-2 also seems broken compared with the provided documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
