### ISSUE TITLE
Support routing key binding patterns for AMQP topic exchanges

### ISSUE THREAD

**Issue by kvaleev** [asyncapi/bindings#26]
#### Reason/Context

Currently, AsyncAPI AMQP 0-9-1 Bindings object doesn't support the routing schema for [topic exchanges](https://www.cloudamqp.com/blog/2015-09-03-part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html#topic-exchange).

Having the ability to specify patterns for a routing key will make it possible to describe routing messages to queues based on wildcard matches between the routing key and the routing pattern.
 
#### Description

One of the first comer ways to do so is to add an optional `pattern` field to the `queue` binding object that set regular expression for binding the queue and routing key:

```
channels:
  user/signedup:
    bindings:
      amqp:
        is: routingKey
        queue:
          name: my-queue-name
          pattern:  "user*"
          durable: true
          exclusive: true
          autoDelete: false
          vhost: /
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
        bindingVersion: 0.1.0
```

However, at second glance it's not so simple, as a pattern matching allows us to have several queues for one binding key which means that we may have several different queues for one channel, so maybe it's better to allow an array here:

```
channels:
  user/signedup:
    bindings:
      amqp:
        is: routingKey
        queue:
        - name: my-queue-name
          pattern:  "user*"
          durable: true
          exclusive: true
          autoDelete: false
          vhost: /
        - name: my-another-queue-name
          pattern:  "user/signed*"
          durable: true
          exclusive: true
          autoDelete: false
          vhost: /
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
        bindingVersion: 0.1.0
```
