### ISSUE TITLE
[BUG] JMS server binding properties incorrect type

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/bindings#269]
### Describe the bug.

I'm looking at the JMS server binding and the `properties` and its type is `Schema Array`, which points to a non-existing place 🤔 By looking at the example, the properties have the following shape:

```
properties:
  - name: nameOfTheProperty1
    value: valueOfTheProperty1
  - name: nameOfTheProperty2
    value: valueOfTheProperty2
 ...
```

This is definitely not an array of schemas 😄 So I'm thinking there may be a typo there. In fact, looking at the JSON Schema definition, we got this: https://github.com/asyncapi/spec-json-schemas/blob/master/bindings/jms/0.0.1/server.json#L21.

@rcoppen @SrfHead 

### Expected behavior

To have a well-defined shape.

### Screenshots

No screenshots.

### How to Reproduce

N/A

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it
