### ISSUE TITLE
[FEATURE REQUEST] MuleSoft Anypoint MQ Support

### ISSUE THREAD

**Issue by kokokruunch** [asyncapi/bindings#27]
#### Reason/Context
It would be great to include a support for MuleSoft Anypoint MQ bindings. This will help define async APIs that integrate well with MQ.

#### Description
Introduction of a new binding, that supports Server, Channel, Operation and Message Bindings. 

For example (Channel Binding):
```
channels:
  user/registered:
    bindings:
      anypointmq:
        queue:
          name: queue-name
          ackTimeout: 10000
          encrypted: true
          messageTTL: 10000
        exchange:
          name: exchange-name
          encrypted: true
          boundedQueues:
             - queue-name
        bindingVersion: 0.1.0
```
and 

(Operation Binding - derived from [here](https://docs.mulesoft.com/connectors/anypoint-mq/2.x/anypoint-mq-connector-reference)):
```
channels:
  user/registered:
    subscribe:
      bindings:
        anypointmq:
          expiration: 100000
          ackMode: guest
          ackTimeout: 10000
          pollTime: 100000
          bindingVersion: 0.1.0
```

It will be similar to how amqp bindings are defined. I've got something ready to be PR'd, once this Feature request is reviewed.
