### ISSUE TITLE
Understanding WebSocket API description's query and Chanels Object keys

### ISSUE THREAD

**Issue by bali182** [asyncapi/bindings#68]
Hello, I'm raising this issue  to have a better understanding how the ws protocol is described. I'm looking at this example: 

https://github.com/asyncapi/spec/blob/master/examples/2.0.0/websocket-gemini.yml

1. When using websockets, the keys in `Channels Object` are the URLs to connect to right?  So this:
```yaml
channels:
  /v1/marketdata/{symbol}:
```

Would mean connect to this URI (where symbol is a parameter), right?:
```ts
//                  in servers              in the channel
new WebSocket("wss://api.gemini.com" + "/v1/marketdata/{symbol}")
```

If we have multiple entries in the `Channels Object` does that mean we can connect to multiple endpoints with their respective parameters and available subscriptions/publishes?

2. What is query under ws bindings? Is that something that has to be turned into a query string when establishing the connection? So this:

```yaml
query:
  type: object
  properties:
    heartbeat:
      type: boolean
      default: false
    top_of_book:
      type: boolean
      default: false
    bids:
      type: boolean
      default: true
    ...
```
Would also go into the URI?
```ts
new WebSocket("wss://api.gemini.com" + "/v1/marketdata/{symbol}?heartbeat=...&top_of_book=...")
```
In case yes, how to serialize the fields of this object? I saw that it must be an object with properties in the docs, but can the properties objects themselves? If so how deeply nested can this structure go and what would be the serialization method for it? OpenAPI has a nightmarish amount of parameter serialization methods, I hope you went with a simpler approach :D

In case I'm completely wrong please advise!

**Comment by bali182** [comment]
Cool thank you for moving it!

> I mean, how would the resulting query param look like for such example?

That is exactly my question :)  JSON Schema allows it. AsyncAPI docs don't say as far as I have seen that you can't do this.  So my question is:

A) Is nesting not allowed, and this info missing from the docs?
B) If nesting is allowed are there specs on serialization?

Assume we have the schema you mentioned:

```yaml
query:
  type: object
  properties:
    heartbeat:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: number
```

OpenAPI would prescribe serializition of the equivalent like:
style: form, explode: true -> `?foo=someString&bar=1`
style: form, explode: false -> `?heartbeat=foo,someString,bar,1`
style: deepObject, explode: true -> `?heartbeat[foo]=someString&heartbeat[bar]=1`

Its described here: https://swagger.io/docs/specification/serialization/

The purpose of their `ParameterObject` is to describe this.

However if it would look like this (so nested object in a parameter):
```yaml
 ...
        foo:
          type: object
          properties:
            foobar: 
               type: string

```
OpenAPI does not allow this according to spec.

I'm looking for the AsyncAPI equivalent of this doc basically: https://swagger.io/docs/specification/serialization/ if it exists.

Thank you:
Balazs
